language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - freny.ng@outlook.com
    on_success: always
    on_failure: always

branches:
  only:
   - development

before_script:
  - npm install -g @angular/cli
  - npm install -g now
  - npm audit fix

script:
  - ng lint
  - ng build --prod --base-href https://freny-n.github.io/bitcoin-order-app/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development

after_success:
 - git push origin :development